### PR TITLE
Add misc/replit-api

### PR DESCRIPTION
**Pull request by CoolCoderSJ**
Many people have been asking for an API for Replit, so since crosis has been shut down, I wrote this small tutorial to help people use the /data/ endpoints to get data easily.

### CODE REVIEW

**Comment by RayhanADev** [comment]
There are many, many, many more endpoints than those two (I've been led to believe) and the Replit API is *suppose* to be private but few people care.

~~Please include [my package](https://github.com/ReplAPI-it/ReplAPI.it) in the tutorial since it's clearly the best.~~

**Comment by CoolCoderSJ** [comment]
Those are the two I know, so I've written them down. If there are more, it can be added. The reason why I say its public is because no authentication is required, an anonymous user can look up all of that data.

**Comment by masad-frost** [comment]
Hello guys. Thank you for sending a pull request for this, I appreciate the energy. Unfortunately at this time we cannot accept this pull request. Our API is private and is not meant for public use, ie it's only supposed to be used by clients we officially support.

The API constantly changes and is subject to breakage at our discretion. In addition this API does not have security measures for public use. We do not block or ban people from using it because we like what the community has been building with it and it is a motivator for us to create a public/open API

Again I love this energy, but we'll have to close the PR at this time. Public APIs are going to be a huge focus for us this fall and hopefully we'll have something flushed out by then.

**Comment by RayhanADev** [comment]
@masad-frost makes sense, ~~do I have official approval for my package or is that no~~

**Pull request closed without merging**
